export const sampleCirculars = [
    {
        id: 'circ-001',
        title: 'RBI/2023-24/87 - Prudential Norms for Classification of Advances',
        date: '2023-12-15',
        source_url: 'https://rbi.org.in/Scripts/NotificationUser.aspx?Id=12345',
        full_text: 'In exercise of the powers conferred by Section 35A of the Banking Regulation Act, 1949, the Reserve Bank of India hereby issues the following directions to all Scheduled Commercial Banks...',
        ingested_at: '2024-01-10T10:30:00Z',
        status: 'active',
    },
    {
        id: 'circ-002',
        title: 'RBI/2023-24/92 - Guidelines on Loan-to-Value Ratio',
        date: '2024-01-20',
        source_url: 'https://rbi.org.in/Scripts/NotificationUser.aspx?Id=12346',
        full_text: 'With a view to ensuring prudent risk management practices, it has been decided to prescribe the following guidelines for computation of Loan-to-Value (LTV) ratio...',
        ingested_at: '2024-01-25T14:15:00Z',
        status: 'active',
    },
    {
        id: 'circ-003',
        title: 'RBI/2023-24/95 - Exposure Norms for Single Borrower',
        date: '2024-02-05',
        source_url: 'https://rbi.org.in/Scripts/NotificationUser.aspx?Id=12347',
        full_text: 'In terms of the existing instructions, the exposure of a bank to a single borrower shall not exceed 15% of its capital funds...',
        ingested_at: '2024-02-10T09:45:00Z',
        status: 'active',
    },
];
export const sampleRules = [
    {
        id: 'rule-001',
        title: 'Maximum Loan Amount for Personal Loans',
        description: 'Personal loans to individuals shall not exceed Rs. 20 lakhs without additional collateral',
        conditions: [
            {
                field: 'loan_type',
                operator: 'eq',
                value: 'personal',
                logical_operator: 'AND',
            },
            {
                field: 'loan_amount',
                operator: 'gt',
                value: 2000000,
            },
        ],
        action: 'DENY',
        source_section: 'Section 4.2.1',
        confidence_score: 0.95,
        circular_id: 'circ-001',
        created_at: '2024-01-10T10:35:00Z',
        updated_at: '2024-01-10T10:35:00Z',
        full_json: {
            rule_id: 'rule-001',
            conditions: [
                { field: 'loan_type', operator: 'eq', value: 'personal' },
                { field: 'loan_amount', operator: 'gt', value: 2000000 },
            ],
            action: 'DENY',
            metadata: {
                source: 'RBI Circular 87/2023',
                section: '4.2.1',
            },
        },
    },
    {
        id: 'rule-002',
        title: 'LTV Ratio for Home Loans',
        description: 'Loan-to-Value ratio for home loans shall not exceed 80% for loans above Rs. 30 lakhs',
        conditions: [
            {
                field: 'loan_type',
                operator: 'eq',
                value: 'home',
                logical_operator: 'AND',
            },
            {
                field: 'loan_amount',
                operator: 'gt',
                value: 3000000,
                logical_operator: 'AND',
            },
            {
                field: 'ltv_ratio',
                operator: 'gt',
                value: 0.80,
            },
        ],
        action: 'DENY',
        source_section: 'Section 3.1.2',
        confidence_score: 0.92,
        circular_id: 'circ-002',
        created_at: '2024-01-25T14:20:00Z',
        updated_at: '2024-01-25T14:20:00Z',
        full_json: {
            rule_id: 'rule-002',
            conditions: [
                { field: 'loan_type', operator: 'eq', value: 'home' },
                { field: 'loan_amount', operator: 'gt', value: 3000000 },
                { field: 'ltv_ratio', operator: 'gt', value: 0.80 },
            ],
            action: 'DENY',
            metadata: {
                source: 'RBI Circular 92/2023',
                section: '3.1.2',
            },
        },
    },
    {
        id: 'rule-003',
        title: 'Single Borrower Exposure Limit',
        description: 'Exposure to single borrower shall not exceed 15% of capital funds',
        conditions: [
            {
                field: 'borrower_exposure',
                operator: 'gt',
                value: 0.15,
            },
        ],
        action: 'FLAG',
        source_section: 'Section 2.3',
        confidence_score: 0.88,
        circular_id: 'circ-003',
        created_at: '2024-02-10T09:50:00Z',
        updated_at: '2024-02-10T09:50:00Z',
        full_json: {
            rule_id: 'rule-003',
            conditions: [
                { field: 'borrower_exposure', operator: 'gt', value: 0.15 },
            ],
            action: 'FLAG',
            metadata: {
                source: 'RBI Circular 95/2023',
                section: '2.3',
            },
        },
    },
    {
        id: 'rule-004',
        title: 'Agricultural Loan Tenure',
        description: 'Agricultural loans shall have minimum tenure of 12 months',
        conditions: [
            {
                field: 'loan_type',
                operator: 'eq',
                value: 'agricultural',
                logical_operator: 'AND',
            },
            {
                field: 'tenure',
                operator: 'lt',
                value: 12,
            },
        ],
        action: 'DENY',
        source_section: 'Section 5.1',
        confidence_score: 0.91,
        circular_id: 'circ-001',
        created_at: '2024-01-10T10:40:00Z',
        updated_at: '2024-01-10T10:40:00Z',
        full_json: {
            rule_id: 'rule-004',
            conditions: [
                { field: 'loan_type', operator: 'eq', value: 'agricultural' },
                { field: 'tenure', operator: 'lt', value: 12 },
            ],
            action: 'DENY',
            metadata: {
                source: 'RBI Circular 87/2023',
                section: '5.1',
            },
        },
    },
    {
        id: 'rule-005',
        title: 'Business Loan Interest Rate Cap',
        description: 'Business loans shall not exceed 18% annual interest rate',
        conditions: [
            {
                field: 'loan_type',
                operator: 'eq',
                value: 'business',
                logical_operator: 'AND',
            },
            {
                field: 'interest_rate',
                operator: 'gt',
                value: 18,
            },
        ],
        action: 'DENY',
        source_section: 'Section 6.2',
        confidence_score: 0.89,
        circular_id: 'circ-002',
        created_at: '2024-01-25T14:25:00Z',
        updated_at: '2024-01-25T14:25:00Z',
        full_json: {
            rule_id: 'rule-005',
            conditions: [
                { field: 'loan_type', operator: 'eq', value: 'business' },
                { field: 'interest_rate', operator: 'gt', value: 18 },
            ],
            action: 'DENY',
            metadata: {
                source: 'RBI Circular 92/2023',
                section: '6.2',
            },
        },
    },
    {
        id: 'rule-006',
        title: 'Purpose Code Required For Outward Remittance',
        description: 'Resident outward remittances must include a valid declared purpose code before processing.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'forex',
                logical_operator: 'AND',
            },
            {
                field: 'scenario_type',
                operator: 'eq',
                value: 'outward_remittance',
                logical_operator: 'AND',
            },
            {
                field: 'fx_purpose_code',
                operator: 'eq',
                value: '',
            },
        ],
        action: 'FLAG',
        source_section: 'FEMA Current Account Transactions',
        confidence_score: 0.9,
        circular_id: 'circ-003',
        created_at: '2024-02-15T10:15:00Z',
        updated_at: '2024-02-15T10:15:00Z',
        full_json: {
            rule_id: 'rule-006',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'forex' },
                { field: 'scenario_type', operator: 'eq', value: 'outward_remittance' },
                { field: 'fx_purpose_code', operator: 'eq', value: '' },
            ],
            action: 'FLAG',
            metadata: {
                source: 'FEMA outward remittance controls',
                section: 'Purpose declaration',
            },
        },
    },
    {
        id: 'rule-007',
        title: 'Hedging Requires Underlying Exposure',
        description: 'Derivative hedging requests should be backed by documented underlying exposure.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'forex',
                logical_operator: 'AND',
            },
            {
                field: 'hedging_flag',
                operator: 'eq',
                value: 'yes',
                logical_operator: 'AND',
            },
            {
                field: 'underlying_exposure_exists',
                operator: 'eq',
                value: 'no',
            },
        ],
        action: 'DENY',
        source_section: 'Derivative Suitability Controls',
        confidence_score: 0.94,
        circular_id: 'circ-003',
        created_at: '2024-02-15T10:20:00Z',
        updated_at: '2024-02-15T10:20:00Z',
        full_json: {
            rule_id: 'rule-007',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'forex' },
                { field: 'hedging_flag', operator: 'eq', value: 'yes' },
                { field: 'underlying_exposure_exists', operator: 'eq', value: 'no' },
            ],
            action: 'DENY',
            metadata: {
                source: 'FX hedging risk management guidance',
                section: 'Underlying exposure validation',
            },
        },
    },
    {
        id: 'rule-008',
        title: 'Restricted Securities Cannot Be Traded Freely',
        description: 'Orders in securities on the restricted list should be blocked pending compliance clearance.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'trading',
                logical_operator: 'AND',
            },
            {
                field: 'restricted_list_flag',
                operator: 'eq',
                value: 'yes',
            },
        ],
        action: 'DENY',
        source_section: 'Restricted List Surveillance',
        confidence_score: 0.96,
        circular_id: 'circ-003',
        created_at: '2024-02-18T09:30:00Z',
        updated_at: '2024-02-18T09:30:00Z',
        full_json: {
            rule_id: 'rule-008',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'trading' },
                { field: 'restricted_list_flag', operator: 'eq', value: 'yes' },
            ],
            action: 'DENY',
            metadata: {
                source: 'Dealer restricted-list controls',
                section: 'Pre-trade surveillance',
            },
        },
    },
    {
        id: 'rule-009',
        title: 'Inside Information Risk Requires Manual Review',
        description: 'Potential insider-information exposure should trigger a review workflow before execution.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'trading',
                logical_operator: 'AND',
            },
            {
                field: 'insider_flag',
                operator: 'eq',
                value: 'yes',
            },
        ],
        action: 'FLAG',
        source_section: 'Insider Trading Prevention',
        confidence_score: 0.93,
        circular_id: 'circ-003',
        created_at: '2024-02-18T09:40:00Z',
        updated_at: '2024-02-18T09:40:00Z',
        full_json: {
            rule_id: 'rule-009',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'trading' },
                { field: 'insider_flag', operator: 'eq', value: 'yes' },
            ],
            action: 'FLAG',
            metadata: {
                source: 'Insider trading controls',
                section: 'Surveillance escalation',
            },
        },
    },
    {
        id: 'rule-010',
        title: 'Retail Investors Should Not Access Private Placement Bonds',
        description: 'Retail investors are not suitable participants for unlisted private placement bond offerings.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'bonds',
                logical_operator: 'AND',
            },
            {
                field: 'private_placement_flag',
                operator: 'eq',
                value: 'yes',
                logical_operator: 'AND',
            },
            {
                field: 'investor_category',
                operator: 'eq',
                value: 'retail',
            },
        ],
        action: 'DENY',
        source_section: 'Private Placement Suitability',
        confidence_score: 0.95,
        circular_id: 'circ-002',
        created_at: '2024-02-19T11:00:00Z',
        updated_at: '2024-02-19T11:00:00Z',
        full_json: {
            rule_id: 'rule-010',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'bonds' },
                { field: 'private_placement_flag', operator: 'eq', value: 'yes' },
                { field: 'investor_category', operator: 'eq', value: 'retail' },
            ],
            action: 'DENY',
            metadata: {
                source: 'Debt placement suitability framework',
                section: 'Investor access restrictions',
            },
        },
    },
    {
        id: 'rule-011',
        title: 'Lower-Rated Unsecured Bonds Need Review',
        description: 'Lower-rated unsecured debt should be escalated before acceptance into standard portfolios.',
        conditions: [
            {
                field: 'domain',
                operator: 'eq',
                value: 'bonds',
                logical_operator: 'AND',
            },
            {
                field: 'credit_rating',
                operator: 'eq',
                value: 'BB',
                logical_operator: 'AND',
            },
            {
                field: 'secured_flag',
                operator: 'eq',
                value: 'no',
            },
        ],
        action: 'FLAG',
        source_section: 'Debt Risk Escalation',
        confidence_score: 0.89,
        circular_id: 'circ-002',
        created_at: '2024-02-19T11:15:00Z',
        updated_at: '2024-02-19T11:15:00Z',
        full_json: {
            rule_id: 'rule-011',
            conditions: [
                { field: 'domain', operator: 'eq', value: 'bonds' },
                { field: 'credit_rating', operator: 'eq', value: 'BB' },
                { field: 'secured_flag', operator: 'eq', value: 'no' },
            ],
            action: 'FLAG',
            metadata: {
                source: 'Debt portfolio review controls',
                section: 'Credit-quality escalation',
            },
        },
    },
];
export const sampleDashboardStats = {
    total_circulars: 3,
    total_rules: 5,
    success_rate: 0.85,
    failure_rate: 0.15,
    recent_ingestions: [
        {
            id: 'circ-003',
            title: 'Exposure Norms for Single Borrower',
            ingested_at: '2024-02-10T09:45:00Z',
            rules_extracted: 1,
        },
        {
            id: 'circ-002',
            title: 'Guidelines on Loan-to-Value Ratio',
            ingested_at: '2024-01-25T14:15:00Z',
            rules_extracted: 2,
        },
        {
            id: 'circ-001',
            title: 'Prudential Norms for Classification of Advances',
            ingested_at: '2024-01-10T10:30:00Z',
            rules_extracted: 2,
        },
    ],
};
export const sampleEvaluationResult = {
    id: 'eval-001',
    input: {
        domain: 'lending',
        regulator: 'RBI',
        jurisdiction: 'India',
        scenario_type: 'retail_loan',
        borrower_type: 'individual',
        loan_amount: 3000000,
        loan_type: 'personal',
        tenure: 24,
        interest_rate: 14.5,
        collateral_type: 'property',
    },
    result: 'DENY',
    matching_rules: [sampleRules[0]],
    failed_rules: [sampleRules[0]],
    debug_trace: [
        {
            field: 'loan_type',
            expected: 'personal',
            actual: 'personal',
            result: 'PASS',
            rule_id: 'rule-001',
            rule_title: 'Maximum Loan Amount for Personal Loans',
        },
        {
            field: 'loan_amount',
            expected: '≤ 2000000',
            actual: 3000000,
            result: 'FAIL',
            rule_id: 'rule-001',
            rule_title: 'Maximum Loan Amount for Personal Loans',
        },
    ],
    evaluated_at: '2024-02-15T11:30:00Z',
};
