export const buildInitialInput = (domain) => {
    const base = {
        domain,
        regulator: domain === 'forex'
            ? 'RBI FEMA'
            : domain === 'trading'
                ? 'SEBI'
                : domain === 'bonds'
                    ? 'SEBI / RBI'
                    : 'RBI',
        jurisdiction: 'India',
    };
    if (domain === 'forex') {
        return {
            ...base,
            scenario_type: 'outward_remittance',
            customer_type: 'individual',
            institution_type: 'authorized_dealer_bank',
            currency: 'USD',
            amount: 0,
            country: 'India',
            counterparty_country: '',
            resident_status: 'resident',
            remittance_type: 'current_account',
            fx_purpose_code: '',
            buy_or_sell: 'buy',
            currency_pair: 'USD/INR',
            hedging_flag: 'no',
            underlying_exposure_exists: 'no',
            exposure_amount: 0,
            tenor_days: 0,
        };
    }
    if (domain === 'trading') {
        return {
            ...base,
            scenario_type: 'equity_trade',
            customer_type: 'retail',
            institution_type: 'broker',
            instrument_type: 'equity',
            market_segment: 'cash',
            order_type: 'market',
            trade_side: 'buy',
            trade_value: 0,
            settlement_type: 'delivery',
            client_category: 'retail',
            restricted_list_flag: 'no',
            insider_flag: 'no',
            margin_used: 0,
        };
    }
    if (domain === 'bonds') {
        return {
            ...base,
            scenario_type: 'bond_investment',
            customer_type: 'investor',
            institution_type: 'bank',
            issuer_type: 'corporate',
            bond_type: 'listed_corporate_bond',
            credit_rating: 'AA',
            maturity_tenor: 5,
            coupon_type: 'fixed',
            yield_percent: 7.5,
            listing_status: 'listed',
            secured_flag: 'yes',
            private_placement_flag: 'no',
            investor_category: 'institutional',
            amount: 0,
        };
    }
    return {
        ...base,
        scenario_type: 'retail_loan',
        borrower_type: 'individual',
        customer_type: 'retail',
        institution_type: 'scheduled_commercial_bank',
        loan_type: 'home',
        loan_amount: 0,
        tenure: 0,
        interest_rate: 0,
        collateral_type: 'property',
    };
};
export const simulatorDomains = [
    {
        id: 'lending',
        label: 'Lending',
        description: 'Retail and commercial loan scenarios across borrower, collateral, pricing, and tenor rules.',
        regulators: ['RBI'],
        jurisdictions: ['India'],
        hero: 'Explore credit policy, exposure, eligibility, and pricing decisions.',
        fields: [
            {
                key: 'scenario_type',
                label: 'Scenario Type',
                type: 'select',
                options: [
                    { label: 'Retail Loan', value: 'retail_loan' },
                    { label: 'Commercial Loan', value: 'commercial_loan' },
                    { label: 'Agricultural Loan', value: 'agri_loan' },
                ],
            },
            {
                key: 'borrower_type',
                label: 'Borrower Type',
                type: 'select',
                options: [
                    { label: 'Individual', value: 'individual' },
                    { label: 'Business', value: 'business' },
                    { label: 'Corporate', value: 'corporate' },
                ],
            },
            {
                key: 'loan_type',
                label: 'Loan Type',
                type: 'select',
                options: [
                    { label: 'Home', value: 'home' },
                    { label: 'Personal', value: 'personal' },
                    { label: 'Business', value: 'business' },
                    { label: 'Agricultural', value: 'agricultural' },
                    { label: 'Education', value: 'education' },
                ],
            },
            { key: 'loan_amount', label: 'Loan Amount (INR)', type: 'number', placeholder: 'e.g. 5000000' },
            { key: 'tenure', label: 'Tenure (months)', type: 'number', placeholder: 'e.g. 60' },
            { key: 'interest_rate', label: 'Interest Rate (%)', type: 'number', placeholder: 'e.g. 8.75' },
            {
                key: 'collateral_type',
                label: 'Collateral Type',
                type: 'select',
                options: [
                    { label: 'Property', value: 'property' },
                    { label: 'Vehicle', value: 'vehicle' },
                    { label: 'Fixed Deposit', value: 'fd' },
                    { label: 'Gold', value: 'gold' },
                    { label: 'None', value: 'none' },
                ],
            },
        ],
    },
    {
        id: 'forex',
        label: 'Forex',
        description: 'Cross-border currency and remittance scenarios across FEMA-style checks and dealer controls.',
        regulators: ['RBI FEMA', 'Authorized Dealer Policy'],
        jurisdictions: ['India'],
        hero: 'Simulate remittances, hedging, purpose-code, and exposure validations.',
        fields: [
            {
                key: 'scenario_type',
                label: 'Scenario Type',
                type: 'select',
                options: [
                    { label: 'Outward Remittance', value: 'outward_remittance' },
                    { label: 'Import Payment', value: 'import_payment' },
                    { label: 'Hedging Request', value: 'hedging_request' },
                ],
            },
            {
                key: 'customer_type',
                label: 'Customer Type',
                type: 'select',
                options: [
                    { label: 'Individual', value: 'individual' },
                    { label: 'SME', value: 'sme' },
                    { label: 'Corporate', value: 'corporate' },
                ],
            },
            {
                key: 'resident_status',
                label: 'Resident Status',
                type: 'select',
                options: [
                    { label: 'Resident', value: 'resident' },
                    { label: 'Non-Resident', value: 'non_resident' },
                ],
            },
            { key: 'amount', label: 'Transaction Amount', type: 'number', placeholder: 'e.g. 250000' },
            {
                key: 'currency',
                label: 'Currency',
                type: 'select',
                options: [
                    { label: 'USD', value: 'USD' },
                    { label: 'EUR', value: 'EUR' },
                    { label: 'GBP', value: 'GBP' },
                    { label: 'JPY', value: 'JPY' },
                ],
            },
            { key: 'counterparty_country', label: 'Counterparty Country', type: 'text', placeholder: 'e.g. Singapore' },
            {
                key: 'remittance_type',
                label: 'Remittance Type',
                type: 'select',
                options: [
                    { label: 'Current Account', value: 'current_account' },
                    { label: 'Capital Account', value: 'capital_account' },
                ],
            },
            { key: 'fx_purpose_code', label: 'Purpose Code', type: 'text', placeholder: 'e.g. S0001' },
            {
                key: 'buy_or_sell',
                label: 'Buy / Sell',
                type: 'select',
                options: [
                    { label: 'Buy FX', value: 'buy' },
                    { label: 'Sell FX', value: 'sell' },
                ],
            },
            {
                key: 'currency_pair',
                label: 'Currency Pair',
                type: 'select',
                options: [
                    { label: 'USD/INR', value: 'USD/INR' },
                    { label: 'EUR/INR', value: 'EUR/INR' },
                    { label: 'GBP/INR', value: 'GBP/INR' },
                ],
            },
            {
                key: 'hedging_flag',
                label: 'Hedging Requested',
                type: 'select',
                options: [
                    { label: 'No', value: 'no' },
                    { label: 'Yes', value: 'yes' },
                ],
            },
            {
                key: 'underlying_exposure_exists',
                label: 'Underlying Exposure Exists',
                type: 'select',
                options: [
                    { label: 'No', value: 'no' },
                    { label: 'Yes', value: 'yes' },
                ],
            },
            { key: 'exposure_amount', label: 'Underlying Exposure Amount', type: 'number', placeholder: 'e.g. 500000' },
            { key: 'tenor_days', label: 'Tenor (days)', type: 'number', placeholder: 'e.g. 90' },
        ],
    },
    {
        id: 'trading',
        label: 'Trading',
        description: 'Order, market-abuse, client-category, and settlement scenarios for securities trading.',
        regulators: ['SEBI', 'Exchange Controls'],
        jurisdictions: ['India'],
        hero: 'Simulate trade approvals, surveillance triggers, and market-access controls.',
        fields: [
            {
                key: 'scenario_type',
                label: 'Scenario Type',
                type: 'select',
                options: [
                    { label: 'Equity Trade', value: 'equity_trade' },
                    { label: 'Derivatives Trade', value: 'derivatives_trade' },
                    { label: 'Restricted Security Order', value: 'restricted_order' },
                ],
            },
            {
                key: 'client_category',
                label: 'Client Category',
                type: 'select',
                options: [
                    { label: 'Retail', value: 'retail' },
                    { label: 'HNI', value: 'hni' },
                    { label: 'Institutional', value: 'institutional' },
                ],
            },
            {
                key: 'instrument_type',
                label: 'Instrument Type',
                type: 'select',
                options: [
                    { label: 'Equity', value: 'equity' },
                    { label: 'Futures', value: 'futures' },
                    { label: 'Options', value: 'options' },
                    { label: 'ETF', value: 'etf' },
                ],
            },
            {
                key: 'market_segment',
                label: 'Market Segment',
                type: 'select',
                options: [
                    { label: 'Cash', value: 'cash' },
                    { label: 'Derivatives', value: 'derivatives' },
                    { label: 'SME', value: 'sme' },
                ],
            },
            {
                key: 'order_type',
                label: 'Order Type',
                type: 'select',
                options: [
                    { label: 'Market', value: 'market' },
                    { label: 'Limit', value: 'limit' },
                    { label: 'Margin', value: 'margin' },
                ],
            },
            {
                key: 'trade_side',
                label: 'Trade Side',
                type: 'select',
                options: [
                    { label: 'Buy', value: 'buy' },
                    { label: 'Sell', value: 'sell' },
                ],
            },
            { key: 'trade_value', label: 'Trade Value (INR)', type: 'number', placeholder: 'e.g. 2500000' },
            {
                key: 'settlement_type',
                label: 'Settlement Type',
                type: 'select',
                options: [
                    { label: 'Delivery', value: 'delivery' },
                    { label: 'Intraday', value: 'intraday' },
                    { label: 'T+1', value: 't1' },
                ],
            },
            {
                key: 'restricted_list_flag',
                label: 'Restricted List Security',
                type: 'select',
                options: [
                    { label: 'No', value: 'no' },
                    { label: 'Yes', value: 'yes' },
                ],
            },
            {
                key: 'insider_flag',
                label: 'Inside Information Risk',
                type: 'select',
                options: [
                    { label: 'No', value: 'no' },
                    { label: 'Yes', value: 'yes' },
                ],
            },
            { key: 'margin_used', label: 'Margin Used (%)', type: 'number', placeholder: 'e.g. 55' },
        ],
    },
    {
        id: 'bonds',
        label: 'Bonds',
        description: 'Debt-market scenarios across listing, placement, rating, tenor, and investor suitability.',
        regulators: ['SEBI / RBI', 'Debt Listing Framework'],
        jurisdictions: ['India'],
        hero: 'Explore bond issuance and investment suitability across debt-market controls.',
        fields: [
            {
                key: 'scenario_type',
                label: 'Scenario Type',
                type: 'select',
                options: [
                    { label: 'Bond Investment', value: 'bond_investment' },
                    { label: 'Private Placement', value: 'private_placement' },
                    { label: 'Treasury Allocation', value: 'treasury_allocation' },
                ],
            },
            {
                key: 'issuer_type',
                label: 'Issuer Type',
                type: 'select',
                options: [
                    { label: 'Government', value: 'government' },
                    { label: 'Corporate', value: 'corporate' },
                    { label: 'NBFC', value: 'nbfc' },
                ],
            },
            {
                key: 'bond_type',
                label: 'Bond Type',
                type: 'select',
                options: [
                    { label: 'Listed Corporate Bond', value: 'listed_corporate_bond' },
                    { label: 'Private Placement Bond', value: 'private_placement_bond' },
                    { label: 'Government Security', value: 'gsec' },
                ],
            },
            {
                key: 'credit_rating',
                label: 'Credit Rating',
                type: 'select',
                options: [
                    { label: 'AAA', value: 'AAA' },
                    { label: 'AA', value: 'AA' },
                    { label: 'A', value: 'A' },
                    { label: 'BBB', value: 'BBB' },
                    { label: 'Below BBB', value: 'BB' },
                ],
            },
            { key: 'amount', label: 'Investment Amount (INR)', type: 'number', placeholder: 'e.g. 10000000' },
            { key: 'maturity_tenor', label: 'Maturity Tenor (years)', type: 'number', placeholder: 'e.g. 7' },
            {
                key: 'coupon_type',
                label: 'Coupon Type',
                type: 'select',
                options: [
                    { label: 'Fixed', value: 'fixed' },
                    { label: 'Floating', value: 'floating' },
                    { label: 'Zero Coupon', value: 'zero_coupon' },
                ],
            },
            { key: 'yield_percent', label: 'Yield (%)', type: 'number', placeholder: 'e.g. 8.25' },
            {
                key: 'listing_status',
                label: 'Listing Status',
                type: 'select',
                options: [
                    { label: 'Listed', value: 'listed' },
                    { label: 'Unlisted', value: 'unlisted' },
                ],
            },
            {
                key: 'secured_flag',
                label: 'Secured Instrument',
                type: 'select',
                options: [
                    { label: 'Yes', value: 'yes' },
                    { label: 'No', value: 'no' },
                ],
            },
            {
                key: 'private_placement_flag',
                label: 'Private Placement',
                type: 'select',
                options: [
                    { label: 'No', value: 'no' },
                    { label: 'Yes', value: 'yes' },
                ],
            },
            {
                key: 'investor_category',
                label: 'Investor Category',
                type: 'select',
                options: [
                    { label: 'Retail', value: 'retail' },
                    { label: 'HNI', value: 'hni' },
                    { label: 'Institutional', value: 'institutional' },
                ],
            },
        ],
    },
];
export const simulatorPresets = [
    {
        id: 'lend-home-safe',
        title: 'Retail Home Loan',
        description: 'A straightforward home-loan case with collateral and moderate pricing.',
        domain: 'lending',
        values: {
            ...buildInitialInput('lending'),
            scenario_type: 'retail_loan',
            borrower_type: 'individual',
            loan_type: 'home',
            loan_amount: 150000,
            tenure: 120,
            interest_rate: 10,
            collateral_type: 'property',
        },
    },
    {
        id: 'lend-business-high-rate',
        title: 'High-Rate Business Loan',
        description: 'Useful for testing pricing-based denial and review rules.',
        domain: 'lending',
        values: {
            ...buildInitialInput('lending'),
            scenario_type: 'commercial_loan',
            borrower_type: 'business',
            loan_type: 'business',
            loan_amount: 4500000,
            tenure: 36,
            interest_rate: 19.5,
            collateral_type: 'none',
        },
    },
    {
        id: 'fx-remittance-clean',
        title: 'Student Fee Remittance',
        description: 'Resident outward remittance with a clear education purpose.',
        domain: 'forex',
        values: {
            ...buildInitialInput('forex'),
            scenario_type: 'outward_remittance',
            customer_type: 'individual',
            resident_status: 'resident',
            amount: 25000,
            currency: 'USD',
            counterparty_country: 'Canada',
            remittance_type: 'current_account',
            fx_purpose_code: 'S0305',
            buy_or_sell: 'buy',
            currency_pair: 'USD/INR',
            hedging_flag: 'no',
            underlying_exposure_exists: 'no',
            exposure_amount: 0,
            tenor_days: 0,
        },
    },
    {
        id: 'fx-hedging-gap',
        title: 'Hedging Without Exposure',
        description: 'Tests whether the rule set catches unsupported hedging requests.',
        domain: 'forex',
        values: {
            ...buildInitialInput('forex'),
            scenario_type: 'hedging_request',
            customer_type: 'corporate',
            resident_status: 'resident',
            amount: 300000,
            currency: 'USD',
            counterparty_country: 'United States',
            remittance_type: 'capital_account',
            fx_purpose_code: 'HEDGE01',
            buy_or_sell: 'buy',
            currency_pair: 'USD/INR',
            hedging_flag: 'yes',
            underlying_exposure_exists: 'no',
            exposure_amount: 0,
            tenor_days: 180,
        },
    },
    {
        id: 'trade-standard-equity',
        title: 'Standard Equity Delivery Trade',
        description: 'Baseline listed-equity trade for a retail client with no surveillance flags.',
        domain: 'trading',
        values: {
            ...buildInitialInput('trading'),
            scenario_type: 'equity_trade',
            client_category: 'retail',
            instrument_type: 'equity',
            market_segment: 'cash',
            order_type: 'market',
            trade_side: 'buy',
            trade_value: 250000,
            settlement_type: 'delivery',
            restricted_list_flag: 'no',
            insider_flag: 'no',
            margin_used: 0,
        },
    },
    {
        id: 'trade-restricted-order',
        title: 'Restricted Security Order',
        description: 'A useful benchmark for testing restricted-list and surveillance rules.',
        domain: 'trading',
        values: {
            ...buildInitialInput('trading'),
            scenario_type: 'restricted_order',
            client_category: 'hni',
            instrument_type: 'equity',
            market_segment: 'cash',
            order_type: 'limit',
            trade_side: 'buy',
            trade_value: 5000000,
            settlement_type: 'delivery',
            restricted_list_flag: 'yes',
            insider_flag: 'no',
            margin_used: 0,
        },
    },
    {
        id: 'bond-listed-investment',
        title: 'Listed AA Bond Allocation',
        description: 'A plain-vanilla listed debt investment for a professional investor.',
        domain: 'bonds',
        values: {
            ...buildInitialInput('bonds'),
            scenario_type: 'bond_investment',
            issuer_type: 'corporate',
            bond_type: 'listed_corporate_bond',
            credit_rating: 'AA',
            amount: 15000000,
            maturity_tenor: 5,
            coupon_type: 'fixed',
            yield_percent: 7.75,
            listing_status: 'listed',
            secured_flag: 'yes',
            private_placement_flag: 'no',
            investor_category: 'institutional',
        },
    },
    {
        id: 'bond-retail-private-placement',
        title: 'Retail Private Placement Attempt',
        description: 'A comparison case for testing investor-suitability and placement restrictions.',
        domain: 'bonds',
        values: {
            ...buildInitialInput('bonds'),
            scenario_type: 'private_placement',
            issuer_type: 'corporate',
            bond_type: 'private_placement_bond',
            credit_rating: 'BBB',
            amount: 500000,
            maturity_tenor: 8,
            coupon_type: 'floating',
            yield_percent: 10.5,
            listing_status: 'unlisted',
            secured_flag: 'no',
            private_placement_flag: 'yes',
            investor_category: 'retail',
        },
    },
];
